// Arayüz turu: harita, ayarlar, dil değişimi (Türkçe, Arapça/RTL, Japonca), müzik durumu, oyun ekranı.
import { chromium } from 'playwright';
import { pathToFileURL } from 'node:url';
import { mkdirSync } from 'node:fs';
const [file = 'dist/index.html', out = 'shots'] = process.argv.slice(2);
mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined,
  args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, locale: 'en-US' });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('console', (m) => { if (m.type() === 'error' && !m.text().includes('ERR_CERT')) errors.push(m.text()); });
await page.goto(pathToFileURL(file).href);
await page.evaluate(() => { try { localStorage.clear(); } catch {} });
await page.reload();
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/ui-map.png` });
await page.click('[data-open-settings]');
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/ui-settings.png` });
const report = {};
report.languages = await page.evaluate(() => document.querySelectorAll('#set-language option').length);
await page.selectOption('#set-language', 'tr');
await page.waitForTimeout(300);
report.trTitle = await page.textContent('#settings-title');
await page.screenshot({ path: `${out}/ui-settings-tr.png` });
await page.selectOption('#set-language', 'ar');
await page.waitForTimeout(300);
report.dir = await page.evaluate(() => document.documentElement.dir);
await page.click('#btn-settings-close');
await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/ui-map-ar.png` });
await page.click('[data-open-settings]');
await page.selectOption('#set-language', 'ja');
await page.click('#btn-settings-close');
await page.click('#btn-map-play');
await page.waitForFunction(() => window.__cq?.flow.accepting, null, { timeout: 120000 });
await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/ui-game-ja.png` });
report.musicEnabled = await page.evaluate(() => window.__cq.music.isEnabled);
report.audioState = await page.evaluate(() => window.__cq.music.ctx?.state ?? 'none');
report.savedLanguage = await page.evaluate(() => window.__cq.save().settings.language);
console.log(JSON.stringify({ report, errors }));
await browser.close();
